// Mocks generated by Mockito 5.4.6 from annotations
// in naughty_list_notifier/test/features/naughty_list/presentation/naughty_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:naughty_list_notifier/src/shared/firestore/data/firestore_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreRepository extends _i1.Mock
    implements _i2.FirestoreRepository {
  MockFirestoreRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> getDocument(
    String? collection,
    String? docId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDocument, [collection, docId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getCollection(String? collection) =>
      (super.noSuchMethod(
            Invocation.method(#getCollection, [collection]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> setDocument(
    String? collection,
    String? docId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setDocument, [collection, docId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(String? collection, String? docId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [collection, docId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<Map<String, dynamic>?> watchDocument(
    String? collection,
    String? docId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchDocument, [collection, docId]),
            returnValue: _i3.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>?>);

  @override
  _i3.Stream<List<Map<String, dynamic>>> watchCollection(String? collection) =>
      (super.noSuchMethod(
            Invocation.method(#watchCollection, [collection]),
            returnValue: _i3.Stream<List<Map<String, dynamic>>>.empty(),
          )
          as _i3.Stream<List<Map<String, dynamic>>>);
}
