// Mocks generated by Mockito 5.4.6 from annotations
// in naughty_list_notifier/test/features/video_evidence/presentation/video_evidence_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:media_kit/media_kit.dart' as _i4;
import 'package:media_kit_video/media_kit_video.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:naughty_list_notifier/src/features/video_evidence/presentation/video_evidence_controller.dart'
    as _i3;
import 'package:signals_flutter/signals_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignal_0<T> extends _i1.SmartFake implements _i2.Signal<T> {
  _FakeSignal_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoEvidenceController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEvidenceController extends _i1.Mock
    implements _i3.VideoEvidenceController {
  MockVideoEvidenceController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Signal<bool> get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeSignal_0<bool>(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i2.Signal<bool>);

  @override
  _i2.Signal<String?> get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeSignal_0<String?>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i2.Signal<String?>);

  @override
  _i2.Signal<_i4.Player?> get player =>
      (super.noSuchMethod(
            Invocation.getter(#player),
            returnValue: _FakeSignal_0<_i4.Player?>(
              this,
              Invocation.getter(#player),
            ),
          )
          as _i2.Signal<_i4.Player?>);

  @override
  _i2.Signal<_i5.VideoController?> get videoController =>
      (super.noSuchMethod(
            Invocation.getter(#videoController),
            returnValue: _FakeSignal_0<_i5.VideoController?>(
              this,
              Invocation.getter(#videoController),
            ),
          )
          as _i2.Signal<_i5.VideoController?>);

  @override
  _i2.Signal<bool> get isBuffering =>
      (super.noSuchMethod(
            Invocation.getter(#isBuffering),
            returnValue: _FakeSignal_0<bool>(
              this,
              Invocation.getter(#isBuffering),
            ),
          )
          as _i2.Signal<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
